#Postgres database
spring:
  application:
    name: api-requetes
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default-schema: nso
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog.yml
    liquibaseSchemaName: nso



#Log level configuration
logging:
  level:
    org:
      springframework: INFO
    com:
      nsa: INFO


server:
  port: 8081


#Propriétés à moi:
#nsa:
#  prop:
#    chiffre: '999'
#    monProfile: 'global'
#    rownumbers: '1;2;5;10'


